import '../styles/globals.scss'
import type { AppProps } from 'next/app'
import Head from 'next/head';
import BookwormsLayout from '../components/BookwormsLayout';
import { QueryClient, QueryClientProvider } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools';


function MyApp({ Component, pageProps }: AppProps) {
  const queryClient = new QueryClient();
  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>Bookworms!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BookwormsLayout>
        <Component {...pageProps} />
      </BookwormsLayout>
      <ReactQueryDevtools/>
    </QueryClientProvider>
  );
}

export default MyApp
